package business.beans;

// Generated 18-ene-2009 0:32:09 by Hibernate Tools 3.2.4.CR1

/**
 * Assets generated by hbm2java
 */
public class Assets implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6751644147812305372L;
	private Long assPk;
	private String assNombre;
	private String assDescripcion;
	private Long tipAssFk;
	private Long usuFk;
	private Long assFechaAlta;

	public Assets() {
	}

	public Assets(String assNombre, Long tipAssFk, Long usuFk) {
		this.assNombre = assNombre;
		this.tipAssFk = tipAssFk;
		this.usuFk = usuFk;
	}

	public Assets(String assNombre, String assDescripcion, Long tipAssFk,
			Long usuFk) {
		this.assNombre = assNombre;
		this.assDescripcion = assDescripcion;
		this.tipAssFk = tipAssFk;
		this.usuFk = usuFk;
	}

	public Long getAssPk() {
		return this.assPk;
	}

	public void setAssPk(Long assPk) {
		this.assPk = assPk;
	}

	public String getAssNombre() {
		return this.assNombre;
	}

	public void setAssNombre(String assNombre) {
		this.assNombre = assNombre;
	}

	public String getAssDescripcion() {
		return this.assDescripcion;
	}

	public void setAssDescripcion(String assDescripcion) {
		this.assDescripcion = assDescripcion;
	}

	public Long getTipAssFk() {
		return this.tipAssFk;
	}

	public void setTipAssFk(Long tipAssFk) {
		this.tipAssFk = tipAssFk;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public void setAssFechaAlta(Long assFechaAlta) {
		this.assFechaAlta = assFechaAlta;
	}

	public Long getAssFechaAlta() {
		return assFechaAlta;
	}

}
