package business.beans;

// Generated 14-jul-2009 23:26:43 by Hibernate Tools 3.2.4.GA

/**
 * BusquedasPersonales generated by hbm2java
 */
public class BusquedasPersonales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8660423649831909040L;
	private Long busPerPk;
	private long usuFk;
	private long tagFk;
	private long busPerFechaAlta;

	public BusquedasPersonales() {
	}

	public BusquedasPersonales(long usuFk, long tagFk, long busPerFechaAlta) {
		this.usuFk = usuFk;
		this.tagFk = tagFk;
		this.setBusPerFechaAlta(busPerFechaAlta);
	}

	public Long getBusPerPk() {
		return this.busPerPk;
	}

	public void setBusPerPk(Long busPerPk) {
		this.busPerPk = busPerPk;
	}

	public long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(long usuFk) {
		this.usuFk = usuFk;
	}

	public long getTagFk() {
		return this.tagFk;
	}

	public void setTagFk(long tagFk) {
		this.tagFk = tagFk;
	}

	public void setBusPerFechaAlta(long busPerFechaAlta) {
		this.busPerFechaAlta = busPerFechaAlta;
	}

	public long getBusPerFechaAlta() {
		return busPerFechaAlta;
	}

}
