package business.beans;

// Generated 17-ene-2009 23:22:56 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Carpetas generated by hbm2java
 */
public class Carpetas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2122609825081510384L;
	private Long carPk;
	private Assets assets;
	private Carpetas carpetas;
	private Set<Ficheros> ficheroses = new HashSet<Ficheros>(0);
	private Set<Carpetas> carpetases = new HashSet<Carpetas>(0);

	public Carpetas() {
	}

	public Carpetas(Assets assets) {
		this.assets = assets;
	}

	public Carpetas(Assets assets, Carpetas carpetas, Set<Ficheros> ficheroses,
			Set<Carpetas> carpetases) {
		this.assets = assets;
		this.carpetas = carpetas;
		this.ficheroses = ficheroses;
		this.carpetases = carpetases;
	}

	public Long getCarPk() {
		return this.carPk;
	}

	public void setCarPk(Long carPk) {
		this.carPk = carPk;
	}

	public Assets getAssets() {
		return this.assets;
	}

	public void setAssets(Assets assets) {
		this.assets = assets;
	}

	public Carpetas getCarpetas() {
		return this.carpetas;
	}

	public void setCarpetas(Carpetas carpetas) {
		this.carpetas = carpetas;
	}

	public Set<Ficheros> getFicheroses() {
		return this.ficheroses;
	}

	public void setFicheroses(Set<Ficheros> ficheroses) {
		this.ficheroses = ficheroses;
	}

	public Set<Carpetas> getCarpetases() {
		return this.carpetases;
	}

	public void setCarpetases(Set<Carpetas> carpetases) {
		this.carpetases = carpetases;
	}

}
