package business.beans;

// Generated 25-ene-2009 21:19:30 by Hibernate Tools 3.2.4.CR1

/**
 * Cuotas generated by hbm2java
 */
public class Cuotas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1971438910971338348L;
	private Long usuFkPk;
	private Long cuoCuotaDisk;
	private Long cuoCuotaFile;

	public Cuotas() {
	}

	public Cuotas(Long usuFkPk, Long cuoCuotaDisk, Long cuoCuotaFile) {
		this.usuFkPk = usuFkPk;
		this.setCuoCuotaDisk(cuoCuotaDisk);
		this.setCuoCuotaFile(cuoCuotaFile);
	}

	public Long getUsuFkPk() {
		return this.usuFkPk;
	}

	public void setUsuFkPk(Long usuFkPk) {
		this.usuFkPk = usuFkPk;
	}

	public void setCuoCuotaDisk(Long cuoCuotaDisk) {
		this.cuoCuotaDisk = cuoCuotaDisk;
	}

	public Long getCuoCuotaDisk() {
		return cuoCuotaDisk;
	}

	public void setCuoCuotaFile(Long cuoCuotaFile) {
		this.cuoCuotaFile = cuoCuotaFile;
	}

	public Long getCuoCuotaFile() {
		return cuoCuotaFile;
	}

}
