package business.beans;

// Generated 17-ene-2009 23:22:56 by Hibernate Tools 3.2.4.CR1

/**
 * Ficheros generated by hbm2java
 */
public class Ficheros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2512224581760143540L;
	private Long ficPk;
	private Assets assets;
	private Carpetas carpetas;
	private Long ficSize;
	private Long mimFilFk;
	private String ficSysName;
	private String ficChecksum;

	public Ficheros() {
	}

	public Ficheros(Assets assets, Carpetas carpetas, Long ficSize,
			Long mimFilFk, String ficSysName) {
		this.assets = assets;
		this.carpetas = carpetas;
		this.ficSize = ficSize;
		this.mimFilFk = mimFilFk;
		this.setFicSysName(ficSysName);
	}

	public Long getFicPk() {
		return this.ficPk;
	}

	public void setFicPk(Long ficPk) {
		this.ficPk = ficPk;
	}

	public Assets getAssets() {
		return this.assets;
	}

	public void setAssets(Assets assets) {
		this.assets = assets;
	}

	public Carpetas getCarpetas() {
		return this.carpetas;
	}

	public void setCarpetas(Carpetas carpetas) {
		this.carpetas = carpetas;
	}

	public Long getFicSize() {
		return this.ficSize;
	}

	public void setFicSize(Long ficSize) {
		this.ficSize = ficSize;
	}

	public Long getMimFilFk() {
		return this.mimFilFk;
	}

	public void setMimFilFk(Long mimFilFk) {
		this.mimFilFk = mimFilFk;
	}

	public void setFicSysName(String ficSysName) {
		this.ficSysName = ficSysName;
	}

	public String getFicSysName() {
		return ficSysName;
	}

	public void setFicChecksum(String ficChecksum) {
		this.ficChecksum = ficChecksum;
	}

	public String getFicChecksum() {
		return ficChecksum;
	}
}
