package business.beans;
// Generated 19-mar-2009 23:38:43 by Hibernate Tools 3.2.4.GA



/**
 * Links generated by hbm2java
 */
public class Links  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1021341370382539665L;
	private Long linPk;
	private Long assFk;
    private Long assFkRef;

    public Links() {
    }

    public Links(Long assFk, Long assFkRef) {
    	this.assFk = assFk;
    	this.assFkRef = assFkRef;
    }

	public void setLinPk(Long linPk) {
		this.linPk = linPk;
	}

	public Long getLinPk() {
		return linPk;
	}

	public Long getAssFk() {
        return this.assFk;
    }
    
    public void setAssFk(Long assFk) {
        this.assFk = assFk;
    }

	public void setAssFkRef(Long assFkRef) {
		this.assFkRef = assFkRef;
	}

	public Long getAssFkRef() {
		return assFkRef;
	}
 
}


