package business.beans;

// Generated 02-ene-2009 19:01:48 by Hibernate Tools 3.2.4.CR1

/**
 * MimeFiles generated by hbm2java
 */
public class MimeFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1733076666450343178L;
	private Long mimFilPk;
	private String mimFilExtension;
	private String mimFilMime;
	private String mimFilIcon;

	public MimeFiles() {
	}

	public MimeFiles(String mimFilExtension, String mimFilMime) {
		this.mimFilExtension = mimFilExtension;
		this.mimFilMime = mimFilMime;
	}

	public Long getMimFilPk() {
		return this.mimFilPk;
	}

	public void setMimFilPk(Long mimFilPk) {
		this.mimFilPk = mimFilPk;
	}

	public String getMimFilExtension() {
		return this.mimFilExtension;
	}

	public void setMimFilExtension(String mimFilExtension) {
		this.mimFilExtension = mimFilExtension;
	}

	public String getMimFilMime() {
		return this.mimFilMime;
	}

	public void setMimFilMime(String mimFilMime) {
		this.mimFilMime = mimFilMime;
	}

	public void setMimFilIcon(String mimFilIcon) {
		this.mimFilIcon = mimFilIcon;
	}

	public String getMimFilIcon() {
		return mimFilIcon;
	}

}
