package business.beans;

// Generated 23-abr-2009 23:45:15 by Hibernate Tools 3.2.4.GA

/**
 * TagsAsset generated by hbm2java
 */
public class TagsAsset implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5434570530583249166L;
	private Long tagAssPk;
	private long tagFk;
	private long assFk;
	private long usuFk;

	public TagsAsset() {
	}

	public TagsAsset(long tagFk, long assFk, long usuFk) {
		this.tagFk = tagFk;
		this.assFk = assFk;
		this.usuFk = usuFk;
	}

	public Long getTagAssPk() {
		return this.tagAssPk;
	}

	public void setTagAssPk(Long tagAssPk) {
		this.tagAssPk = tagAssPk;
	}

	public long getTagFk() {
		return this.tagFk;
	}

	public void setTagFk(long tagFk) {
		this.tagFk = tagFk;
	}

	public long getAssFk() {
		return this.assFk;
	}

	public void setAssFk(long assFk) {
		this.assFk = assFk;
	}

	public void setUsuFk(long usuFk) {
		this.usuFk = usuFk;
	}

	public long getUsuFk() {
		return usuFk;
	}

}
