package business.beans;

// Generated 17-ene-2009 23:22:56 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiposAssets generated by hbm2java
 */
public class TiposAssets implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 424530419026642302L;
	private Long tipAssPk;
	private String tipAssUkCodigo;
	private String tipAssNombre;
	private String tipAssDescripcion;
	private Set<Assets> assetses = new HashSet<Assets>(0);

	public TiposAssets() {
	}

	public TiposAssets(String tipAssUkCodigo, String tipAssNombre) {
		this.tipAssUkCodigo = tipAssUkCodigo;
		this.tipAssNombre = tipAssNombre;
	}

	public TiposAssets(String tipAssUkCodigo, String tipAssNombre,
			String tipAssDescripcion, Set<Assets> assetses) {
		this.tipAssUkCodigo = tipAssUkCodigo;
		this.tipAssNombre = tipAssNombre;
		this.tipAssDescripcion = tipAssDescripcion;
		this.assetses = assetses;
	}

	public Long getTipAssPk() {
		return this.tipAssPk;
	}

	public void setTipAssPk(Long tipAssPk) {
		this.tipAssPk = tipAssPk;
	}

	public String getTipAssUkCodigo() {
		return this.tipAssUkCodigo;
	}

	public void setTipAssUkCodigo(String tipAssUkCodigo) {
		this.tipAssUkCodigo = tipAssUkCodigo;
	}

	public String getTipAssNombre() {
		return this.tipAssNombre;
	}

	public void setTipAssNombre(String tipAssNombre) {
		this.tipAssNombre = tipAssNombre;
	}

	public String getTipAssDescripcion() {
		return this.tipAssDescripcion;
	}

	public void setTipAssDescripcion(String tipAssDescripcion) {
		this.tipAssDescripcion = tipAssDescripcion;
	}

	public Set<Assets> getAssetses() {
		return this.assetses;
	}

	public void setAssetses(Set<Assets> assetses) {
		this.assetses = assetses;
	}

}
