package common.business.beans;

// Generated 20-mar-2009 18:35:21 by Hibernate Tools 3.2.4.GA

/**
 * BugEstados generated by hbm2java
 */
public class BugEstados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1506512466370313259L;
	private Integer bugEstPk;
	private String bugEstUkCodigo;

	public BugEstados() {
	}

	public BugEstados(String bugEstUkCodigo) {
		this.bugEstUkCodigo = bugEstUkCodigo;
	}

	public Integer getBugEstPk() {
		return this.bugEstPk;
	}

	public void setBugEstPk(Integer bugEstPk) {
		this.bugEstPk = bugEstPk;
	}

	public String getBugEstUkCodigo() {
		return this.bugEstUkCodigo;
	}

	public void setBugEstUkCodigo(String bugEstUkCodigo) {
		this.bugEstUkCodigo = bugEstUkCodigo;
	}

}
