package common.business.beans;

// Generated 20-mar-2009 18:35:21 by Hibernate Tools 3.2.4.GA

/**
 * BugPrioridades generated by hbm2java
 */
public class BugPrioridades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6792144141999383629L;
	private Integer bugPriPk;
	private String bugPriUkCodigo;

	public BugPrioridades() {
	}

	public BugPrioridades(String bugPriUkCodigo) {
		this.bugPriUkCodigo = bugPriUkCodigo;
	}

	public Integer getBugPriPk() {
		return this.bugPriPk;
	}

	public void setBugPriPk(Integer bugPriPk) {
		this.bugPriPk = bugPriPk;
	}

	public String getBugPriUkCodigo() {
		return this.bugPriUkCodigo;
	}

	public void setBugPriUkCodigo(String bugPriUkCodigo) {
		this.bugPriUkCodigo = bugPriUkCodigo;
	}

}
