package common.business.beans;

// Generated 09-feb-2009 23:05:40 by Hibernate Tools 3.2.4.CR1

/**
 * Bugs generated by hbm2java
 */
public class Bugs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5162521065709289784L;
	private Long bugPk;
	private Long bugSite;
	private String bugMessage;
	private String bugDescripcion;
	private Long usuFk;
	private Long bugFechaReport;
	private Long bugEstFk;
	private Long bugPriFk;

	public Bugs() {
	}

	public Bugs(Long usuFk, long bugFechaReport) {
		this.usuFk = usuFk;
		this.bugFechaReport = bugFechaReport;
	}

	public Bugs(Long bugSite, String bugMessage, String bugDescripcion,
			Long usuFk, Long bugFechaReport) {
		this.bugSite = bugSite;
		this.bugMessage = bugMessage;
		this.bugDescripcion = bugDescripcion;
		this.usuFk = usuFk;
		this.bugFechaReport = bugFechaReport;
	}

	public Long getBugPk() {
		return this.bugPk;
	}

	public void setBugPk(Long bugPk) {
		this.bugPk = bugPk;
	}

	public Long getBugSite() {
		return this.bugSite;
	}

	public void setBugSite(Long bugSite) {
		this.bugSite = bugSite;
	}

	public String getBugMessage() {
		return this.bugMessage;
	}

	public void setBugMessage(String bugMessage) {
		this.bugMessage = bugMessage;
	}

	public String getBugDescripcion() {
		return this.bugDescripcion;
	}

	public void setBugDescripcion(String bugDescripcion) {
		this.bugDescripcion = bugDescripcion;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public Long getBugFechaReport() {
		return this.bugFechaReport;
	}

	public void setBugFechaReport(Long bugFechaReport) {
		this.bugFechaReport = bugFechaReport;
	}

	public void setBugEstFk(Long bugEstFk) {
		this.bugEstFk = bugEstFk;
	}

	public Long getBugEstFk() {
		return bugEstFk;
	}

	public void setBugPriFk(Long bugPriFk) {
		this.bugPriFk = bugPriFk;
	}

	public Long getBugPriFk() {
		return bugPriFk;
	}

}
