package common.business.beans;

// Generated 21-mar-2009 0:58:21 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EstadosRelacionUsuarios generated by hbm2java
 */
public class EstadosRelacionUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1920601484827405455L;
	private Long estRelUsuPk;
	private String estRelUsuUkCodigo;
	private Set<RelacionesUsuarios> relacionesUsuarioses = new HashSet<RelacionesUsuarios> (0);

	public EstadosRelacionUsuarios() {
	}

	public EstadosRelacionUsuarios(String estRelUsuUkCodigo) {
		this.estRelUsuUkCodigo = estRelUsuUkCodigo;
	}

	public EstadosRelacionUsuarios(String estRelUsuUkCodigo,
			Set<RelacionesUsuarios> relacionesUsuarioses) {
		this.estRelUsuUkCodigo = estRelUsuUkCodigo;
		this.relacionesUsuarioses = relacionesUsuarioses;
	}

	public Long getEstRelUsuPk() {
		return this.estRelUsuPk;
	}

	public void setEstRelUsuPk(Long estRelUsuPk) {
		this.estRelUsuPk = estRelUsuPk;
	}

	public String getEstRelUsuUkCodigo() {
		return this.estRelUsuUkCodigo;
	}

	public void setEstRelUsuUkCodigo(String estRelUsuUkCodigo) {
		this.estRelUsuUkCodigo = estRelUsuUkCodigo;
	}

	public Set<RelacionesUsuarios> getRelacionesUsuarioses() {
		return this.relacionesUsuarioses;
	}

	public void setRelacionesUsuarioses(Set<RelacionesUsuarios> relacionesUsuarioses) {
		this.relacionesUsuarioses = relacionesUsuarioses;
	}

}
