package common.business.beans;

// Generated 18-dic-2008 23:26:54 by Hibernate Tools 3.2.4.CR1

/**
 * Grupos generated by hbm2java
 */
public class Grupos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2753250553012007979L;
	private Long gruPk;
	private String gruUkCodigo;
	private String gruDescripcion;
	private int gruPrioridad;

	public Grupos() {
	}

	public Grupos(String gruUkCodigo, String gruDescripcion, int gruPrioridad) {
		this.gruUkCodigo = gruUkCodigo;
		this.gruDescripcion = gruDescripcion;
		this.gruPrioridad = gruPrioridad;
	}

	public Long getGruPk() {
		return this.gruPk;
	}

	public void setGruPk(Long gruPk) {
		this.gruPk = gruPk;
	}

	public String getGruUkCodigo() {
		return this.gruUkCodigo;
	}

	public void setGruUkCodigo(String gruUkCodigo) {
		this.gruUkCodigo = gruUkCodigo;
	}

	public String getGruDescripcion() {
		return this.gruDescripcion;
	}

	public void setGruDescripcion(String gruDescripcion) {
		this.gruDescripcion = gruDescripcion;
	}

	public int getGruPrioridad() {
		return this.gruPrioridad;
	}

	public void setGruPrioridad(int gruPrioridad) {
		this.gruPrioridad = gruPrioridad;
	}

}
