package common.business.beans;

// Generated 22-dic-2008 21:10:17 by Hibernate Tools 3.2.4.CR1

/**
 * GruposMenusId generated by hbm2java
 */
public class GruposMenusId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2910149263646169826L;
	private Long gruFk;
	private Long menFk;

	public GruposMenusId() {
	}

	public GruposMenusId(Long gruFk, Long menFk) {
		this.gruFk = gruFk;
		this.menFk = menFk;
	}

	public Long getGruFk() {
		return this.gruFk;
	}

	public void setGruFk(Long gruFk) {
		this.gruFk = gruFk;
	}

	public Long getMenFk() {
		return this.menFk;
	}

	public void setMenFk(Long menFk) {
		this.menFk = menFk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GruposMenusId))
			return false;
		GruposMenusId castOther = (GruposMenusId) other;

		return (this.getGruFk() == castOther.getGruFk())
				&& (this.getMenFk() == castOther.getMenFk());
	}

	public int hashCode() {
		int result = 17;

		result = (int) (37 * result + this.getGruFk());
		result = (int) (37 * result + this.getMenFk());
		return result;
	}

}
