package common.business.beans;

// Generated 22-dic-2008 21:10:17 by Hibernate Tools 3.2.4.CR1

/**
 * GruposMenus generated by hbm2java
 */
public class GruposMenus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6533845714810177638L;
	private GruposMenusId id;

	public GruposMenus() {
	}

	public GruposMenus(GruposMenusId id) {
		this.id = id;
	}

	public GruposMenusId getId() {
		return this.id;
	}

	public void setId(GruposMenusId id) {
		this.id = id;
	}

}
