package common.business.beans;

// Generated 13-jul-2009 23:55:41 by Hibernate Tools 3.2.4.GA

/**
 * Mails generated by hbm2java
 */
public class Mails implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2829454316315817817L;
	private Long maiPk;
	private long aviFk;
	private Long maiFechaAlta;
	private Long maiFechaEnvio;

	public Mails() {
	}

	public Mails(long aviFk, long maiFechaAlta) {
		this.aviFk = aviFk;
		this.maiFechaAlta = maiFechaAlta;
	}

	public Mails(long aviFk, Long maiFechaEnvio, Long maiFechaAlta) {
		this.aviFk = aviFk;
		this.maiFechaEnvio = maiFechaEnvio;
		this.maiFechaAlta = maiFechaAlta;
	}

	public Long getMaiPk() {
		return this.maiPk;
	}

	public void setMaiPk(Long maiPk) {
		this.maiPk = maiPk;
	}

	public long getAviFk() {
		return this.aviFk;
	}

	public void setAviFk(long aviFk) {
		this.aviFk = aviFk;
	}

	public void setMaiFechaAlta(Long maiFechaAlta) {
		this.maiFechaAlta = maiFechaAlta;
	}

	public Long getMaiFechaAlta() {
		return maiFechaAlta;
	}

	public Long getMaiFechaEnvio() {
		return this.maiFechaEnvio;
	}

	public void setMaiFechaEnvio(Long maiFechaEnvio) {
		this.maiFechaEnvio = maiFechaEnvio;
	}

}
