package common.business.beans;

// Generated 21-dic-2008 0:17:08 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Menus generated by hbm2java
 */
public class Menus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6822796830619368060L;
	private Long menPk;
	private Menus menus;
	private String menUkCodigo;
	private String menDescripcion;
	private String menTitulo;
	private Long urlFk;
	private int menOrden;
	private String menIcon;
	private char menPopup;
	private char menRestringido;
	private Set<Menus> menuses = new HashSet<Menus>(0);

	public Menus() {
	}

	public Menus(String menUkCodigo, String menDescripcion, String menTitulo) {
		this.menUkCodigo = menUkCodigo;
		this.menDescripcion = menDescripcion;
		this.menTitulo = menTitulo;
	}

	public Menus(Menus menus, String menUkCodigo, String menDescripcion,
			String menTitulo, Long urlFk, Set<Menus> menuses) {
		this.menus = menus;
		this.menUkCodigo = menUkCodigo;
		this.menDescripcion = menDescripcion;
		this.menTitulo = menTitulo;
		this.urlFk = urlFk;
		this.menuses = menuses;
	}

	public Long getMenPk() {
		return this.menPk;
	}

	public void setMenPk(Long menPk) {
		this.menPk = menPk;
	}

	public Menus getMenus() {
		return this.menus;
	}

	public void setMenus(Menus menus) {
		this.menus = menus;
	}

	public String getMenUkCodigo() {
		return this.menUkCodigo;
	}

	public void setMenUkCodigo(String menUkCodigo) {
		this.menUkCodigo = menUkCodigo;
	}

	public String getMenDescripcion() {
		return this.menDescripcion;
	}

	public void setMenDescripcion(String menDescripcion) {
		this.menDescripcion = menDescripcion;
	}

	public String getMenTitulo() {
		return this.menTitulo;
	}

	public void setMenTitulo(String menTitulo) {
		this.menTitulo = menTitulo;
	}

	public Long getUrlFk() {
		return this.urlFk;
	}

	public void setUrlFk(Long urlFk) {
		this.urlFk = urlFk;
	}

	public void setMenOrden(int menOrden) {
		this.menOrden = menOrden;
	}

	public int getMenOrden() {
		return menOrden;
	}

	public void setMenIcon(String menIcon) {
		this.menIcon = menIcon;
	}

	public String getMenIcon() {
		return menIcon;
	}

	public void setMenPopup(char menPopup) {
		this.menPopup = menPopup;
	}

	public char getMenPopup() {
		return menPopup;
	}

	public void setMenRestringido(char menRestringido) {
		this.menRestringido = menRestringido;
	}

	public char getMenRestringido() {
		return menRestringido;
	}

	public Set<Menus> getMenuses() {
		return this.menuses;
	}

	public void setMenuses(Set<Menus> menuses) {
		this.menuses = menuses;
	}

}
