package common.business.beans;

// Generated 21-mar-2009 0:58:21 by Hibernate Tools 3.2.4.GA

/**
 * RelacionesUsuarios generated by hbm2java
 */
public class RelacionesUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1351989208440068263L;
	private Long relUsuPk;
	private Long estRelUsuFk;
	private Long usu1Fk;
	private Long usu2Fk;
	private Long relUsuFechaRelacion;

	public RelacionesUsuarios() {
	}

	public RelacionesUsuarios(Long estRelUsuFk,
			Long usu1Fk, Long usu2Fk) {
		this.setEstRelUsuFk(estRelUsuFk);
		this.usu1Fk = usu1Fk;
		this.usu2Fk = usu2Fk;
	}

	public Long getRelUsuPk() {
		return this.relUsuPk;
	}

	public void setRelUsuPk(Long relUsuPk) {
		this.relUsuPk = relUsuPk;
	}

	public void setEstRelUsuFk(Long estRelUsuFk) {
		this.estRelUsuFk = estRelUsuFk;
	}

	public Long getEstRelUsuFk() {
		return estRelUsuFk;
	}

	public Long getUsu1Fk() {
		return this.usu1Fk;
	}

	public void setUsu1Fk(Long usu1Fk) {
		this.usu1Fk = usu1Fk;
	}

	public Long getUsu2Fk() {
		return this.usu2Fk;
	}

	public void setUsu2Fk(Long usu2Fk) {
		this.usu2Fk = usu2Fk;
	}

	public void setRelUsuFechaRelacion(Long relUsuFechaRelacion) {
		this.relUsuFechaRelacion = relUsuFechaRelacion;
	}

	public Long getRelUsuFechaRelacion() {
		return relUsuFechaRelacion;
	}
}
