package common.business.beans;

// Generated 20-mar-2009 18:35:21 by Hibernate Tools 3.2.4.GA

/**
 * TiposAvisos generated by hbm2java
 */
public class TiposAvisos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2761536183922483668L;
	private Integer tipAviPk;
	private String tipAviUkCodigo;
	private String tipAviDescripcion;
	private boolean tipAviEnviaMail;

	public TiposAvisos() {
	}

	public TiposAvisos(String tipAviUkCodigo) {
		this.tipAviUkCodigo = tipAviUkCodigo;
	}

	public TiposAvisos(String tipAviUkCodigo, String tipAviDescripcion) {
		this.tipAviUkCodigo = tipAviUkCodigo;
		this.tipAviDescripcion = tipAviDescripcion;
	}

	public Integer getTipAviPk() {
		return this.tipAviPk;
	}

	public void setTipAviPk(Integer tipAviPk) {
		this.tipAviPk = tipAviPk;
	}

	public String getTipAviUkCodigo() {
		return this.tipAviUkCodigo;
	}

	public void setTipAviUkCodigo(String tipAviUkCodigo) {
		this.tipAviUkCodigo = tipAviUkCodigo;
	}

	public String getTipAviDescripcion() {
		return this.tipAviDescripcion;
	}

	public void setTipAviDescripcion(String tipAviDescripcion) {
		this.tipAviDescripcion = tipAviDescripcion;
	}

	public void setTipAviEnviaMail(boolean tipAviEnviaMail) {
		this.tipAviEnviaMail = tipAviEnviaMail;
	}

	public boolean isTipAviEnviaMail() {
		return tipAviEnviaMail;
	}

}
