package common.business.beans;

// Generated 18-dic-2008 19:43:53 by Hibernate Tools 3.2.4.CR1

/**
 * UrlsGruposId generated by hbm2java
 */
public class UrlsGruposId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3790698130708348931L;
	private Long urlFk;
	private Long gruFk;

	public UrlsGruposId() {
	}

	public UrlsGruposId(Long urlFk, Long gruFk) {
		this.urlFk = urlFk;
		this.gruFk = gruFk;
	}

	public Long getUrlFk() {
		return this.urlFk;
	}

	public void setUrlFk(Long urlFk) {
		this.urlFk = urlFk;
	}

	public Long getGruFk() {
		return this.gruFk;
	}

	public void setGruFk(Long gruFk) {
		this.gruFk = gruFk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UrlsGruposId))
			return false;
		UrlsGruposId castOther = (UrlsGruposId) other;

		return (this.getUrlFk() == castOther.getUrlFk())
				&& (this.getGruFk() == castOther.getGruFk());
	}

	public int hashCode() {
		int result = 17;

		result = (int) (37 * result + this.getUrlFk());
		result = (int) (37 * result + this.getGruFk());
		return result;
	}

}
