package common.business.beans;

// Generated 18-dic-2008 19:43:53 by Hibernate Tools 3.2.4.CR1

/**
 * UrlsGrupos generated by hbm2java
 */
public class UrlsGrupos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1008279788386454901L;
	private UrlsGruposId id;
	private Urls urls;

	public UrlsGrupos() {
	}

	public UrlsGrupos(UrlsGruposId id, Urls urls, int urlGruOden) {
		this.id = id;
		this.urls = urls;
	}

	public UrlsGruposId getId() {
		return this.id;
	}

	public void setId(UrlsGruposId id) {
		this.id = id;
	}

	public Urls getUrls() {
		return this.urls;
	}

	public void setUrls(Urls urls) {
		this.urls = urls;
	}

}
