package common.business.beans;

// Generated 17-dic-2008 22:46:15 by Hibernate Tools 3.2.4.CR1

/**
 * UsuariosGruposId generated by hbm2java
 */
public class UsuariosGruposId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3810934270927574185L;
	private Long usuFk;
	private Long gruFk;

	public UsuariosGruposId() {
	}

	public UsuariosGruposId(Long usuFk, Long gruFk) {
		this.usuFk = usuFk;
		this.gruFk = gruFk;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public Long getGruFk() {
		return this.gruFk;
	}

	public void setGruFk(Long gruFk) {
		this.gruFk = gruFk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosGruposId))
			return false;
		UsuariosGruposId castOther = (UsuariosGruposId) other;

		return (this.getUsuFk() == castOther.getUsuFk())
				&& (this.getGruFk() == castOther.getGruFk());
	}

	public int hashCode() {
		int result = 17;

		result = (int) (37 * result + this.getUsuFk());
		result = (int) (37 * result + this.getGruFk());
		return result;
	}

}
