package common.business.beans;

// Generated 17-dic-2008 22:46:15 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4875578452843878248L;
	private Long usuPk;
	private String usuUkCodigo;
	private String usuNombre;
	private String usuApellido1;
	private String usuApellido2;
	private String usuContrasena;
	private Long usuFechaBaja;
	private String usuMail;
	private boolean usuActivo;
	private byte[] usuAvatar;
	private Set<UsuariosGrupos> usuariosGruposes = new HashSet<UsuariosGrupos>(0);
	private boolean usuPublicable;
	private boolean usuRecibeAviso;

	public Usuarios() {
	}

	public Usuarios(String usuUkCodigo, String usuNombre, String usuContrasena) {
		this.usuUkCodigo = usuUkCodigo;
		this.usuNombre = usuNombre;
		this.usuContrasena = usuContrasena;
	}

	public Usuarios(String usuUkCodigo, String usuNombre, String usuContrasena,
			String usuMail, boolean usuActivo) {
		this.usuUkCodigo = usuUkCodigo;
		this.usuNombre = usuNombre;
		this.usuContrasena = usuContrasena;
		this.usuMail = usuMail;
		this.usuActivo = usuActivo;
	}

	public Usuarios(String usuUkCodigo, String usuNombre, String usuApellido1,
			String usuApellido2, String usuContrasena, Long usuFechaBaja,
			String usuMail, boolean usuActivo) {
		this.usuUkCodigo = usuUkCodigo;
		this.usuNombre = usuNombre;
		this.usuApellido1 = usuApellido1;
		this.usuApellido2 = usuApellido2;
		this.usuContrasena = usuContrasena;
		this.usuFechaBaja = usuFechaBaja;
		this.usuMail = usuMail;
		this.usuActivo = usuActivo;
	}

	public Usuarios(String usuUkCodigo, String usuNombre, String usuApellido1,
			String usuApellido2, String usuContrasena, Long usuFechaBaja,
			String usuMail, boolean usuActivo, Set<UsuariosGrupos> usuariosGruposes) {
		this.usuUkCodigo = usuUkCodigo;
		this.usuNombre = usuNombre;
		this.usuApellido1 = usuApellido1;
		this.usuApellido2 = usuApellido2;
		this.usuContrasena = usuContrasena;
		this.usuFechaBaja = usuFechaBaja;
		this.usuMail = usuMail;
		this.usuActivo = usuActivo;
		this.usuariosGruposes = usuariosGruposes;
	}

	public Long getUsuPk() {
		return this.usuPk;
	}

	public void setUsuPk(Long usuPk) {
		this.usuPk = usuPk;
	}

	public String getUsuUkCodigo() {
		return this.usuUkCodigo;
	}

	public void setUsuUkCodigo(String usuUkCodigo) {
		this.usuUkCodigo = usuUkCodigo;
	}

	public String getUsuNombre() {
		return this.usuNombre;
	}

	public void setUsuNombre(String usuNombre) {
		this.usuNombre = usuNombre;
	}

	public String getUsuApellido1() {
		return this.usuApellido1;
	}

	public void setUsuApellido1(String usuApellido1) {
		this.usuApellido1 = usuApellido1;
	}

	public String getUsuApellido2() {
		return this.usuApellido2;
	}

	public void setUsuApellido2(String usuApellido2) {
		this.usuApellido2 = usuApellido2;
	}

	public String getUsuContrasena() {
		return this.usuContrasena;
	}

	public void setUsuContrasena(String usuContrasena) {
		this.usuContrasena = usuContrasena;
	}

	public Long getUsuFechaBaja() {
		return this.usuFechaBaja;
	}

	public void setUsuFechaBaja(Long usuFechaBaja) {
		this.usuFechaBaja = usuFechaBaja;
	}

	public String getUsuMail() {
		return this.usuMail;
	}

	public void setUsuMail(String usuMail) {
		this.usuMail = usuMail;
	}

	public boolean isUsuActivo() {
		return this.usuActivo;
	}

	public void setUsuActivo(boolean usuActivo) {
		this.usuActivo = usuActivo;
	}

	public void setUsuAvatar(byte[] usuAvatar) {
		this.usuAvatar = usuAvatar;
	}

	public byte[] getUsuAvatar() {
		return usuAvatar;
	}

	public Set<UsuariosGrupos> getUsuariosGruposes() {
		return this.usuariosGruposes;
	}

	public void setUsuariosGruposes(Set<UsuariosGrupos> usuariosGruposes) {
		this.usuariosGruposes = usuariosGruposes;
	}

	public void setUsuPublicable(boolean usuPublicable) {
		this.usuPublicable = usuPublicable;
	}

	public boolean isUsuPublicable() {
		return usuPublicable;
	}

	public void setUsuRecibeAviso(boolean usuRecibeAviso) {
		this.usuRecibeAviso = usuRecibeAviso;
	}

	public boolean isUsuRecibeAviso() {
		return usuRecibeAviso;
	}

}
