package common.business.beans;

// Generated 17-dic-2008 22:46:15 by Hibernate Tools 3.2.4.CR1

/**
 * UsuariosGrupos generated by hbm2java
 */
public class UsuariosGrupos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 794847652554541099L;
	private UsuariosGruposId id;
	private Grupos grupos;
	private Usuarios usuarios;

	public UsuariosGrupos() {
	}

	public UsuariosGrupos(UsuariosGruposId id, Grupos grupos, Usuarios usuarios) {
		this.id = id;
		this.grupos = grupos;
		this.usuarios = usuarios;
	}

	public UsuariosGruposId getId() {
		return this.id;
	}

	public void setId(UsuariosGruposId id) {
		this.id = id;
	}

	public Grupos getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Grupos grupos) {
		this.grupos = grupos;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
