package common.business.beans;

// Generated 18-dic-2008 19:43:53 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Zonas generated by hbm2java
 */
public class Zonas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4036474798444227230L;
	private Long zonPk;
	private String zonUkCodigo;
	private String zonDescripcion;
	private Set<Urls> urlses = new HashSet<Urls>(0);

	public Zonas() {
	}

	public Zonas(Long zonPk, String zonUkCodigo, String zonDescripcion) {
		this.zonPk = zonPk;
		this.zonUkCodigo = zonUkCodigo;
		this.zonDescripcion = zonDescripcion;
	}

	public Zonas(String zonUkCodigo, String zonDescripcion) {
		this.zonUkCodigo = zonUkCodigo;
		this.zonDescripcion = zonDescripcion;
	}

	public Zonas(String zonUkCodigo, String zonDescripcion, Set<Urls> urlses) {
		this.zonUkCodigo = zonUkCodigo;
		this.zonDescripcion = zonDescripcion;
		this.urlses = urlses;
	}

	public Long getZonPk() {
		return this.zonPk;
	}

	public void setZonPk(Long zonPk) {
		this.zonPk = zonPk;
	}

	public String getZonUkCodigo() {
		return this.zonUkCodigo;
	}

	public void setZonUkCodigo(String zonUkCodigo) {
		this.zonUkCodigo = zonUkCodigo;
	}

	public String getZonDescripcion() {
		return this.zonDescripcion;
	}

	public void setZonDescripcion(String zonDescripcion) {
		this.zonDescripcion = zonDescripcion;
	}

	public Set<Urls> getUrlses() {
		return this.urlses;
	}

	public void setUrlses(Set<Urls> urlses) {
		this.urlses = urlses;
	}

}
