package business.beans;

// Generated 18-may-2009 23:56:12 by Hibernate Tools 3.2.4.GA

/**
 * Contenidos generated by hbm2java
 */
public class Contenidos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1928879305652699758L;
	private Long conPk;
	private String conData;
	private Long conFechaAlta;
	private Long entFk;
	private Long usuFk;
	private Long conFk;

	public Contenidos() {
	}

	public Contenidos(String conData, Long conFechaAlta, Long entFk, Long usuFk) {
		this.conData = conData;
		this.conFechaAlta = conFechaAlta;
		this.entFk = entFk;
		this.usuFk = usuFk;
	}

	public Contenidos(String conData, Long conFechaAlta, Long entFk, Long usuFk, Long conFk) {
		this.conData = conData;
		this.conFechaAlta = conFechaAlta;
		this.entFk = entFk;
		this.usuFk = usuFk;
		this.conFk = conFk;
	}

	public Long getConPk() {
		return this.conPk;
	}

	public void setConPk(Long conPk) {
		this.conPk = conPk;
	}

	public String getConData() {
		return this.conData;
	}

	public void setConData(String conData) {
		this.conData = conData;
	}

	public long getConFechaAlta() {
		return this.conFechaAlta;
	}

	public void setConFechaAlta(long conFechaAlta) {
		this.conFechaAlta = conFechaAlta;
	}

	public long getEntFk() {
		return this.entFk;
	}

	public void setEntFk(long entFk) {
		this.entFk = entFk;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public void setConFk(Long conFk) {
		this.conFk = conFk;
	}

	public Long getConFk() {
		return conFk;
	}

}
