package business.beans;

// Generated 14-may-2009 22:46:18 by Hibernate Tools 3.2.4.GA

/**
 * DestinosId generated by hbm2java
 */
public class DestinosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3952738186043388496L;
	private Long entFk;
	private Long usuFk;

	public DestinosId() {
	}

	public DestinosId(Long entFk, Long usuFk) {
		this.entFk = entFk;
		this.usuFk = usuFk;
	}

	public Long getEntFk() {
		return this.entFk;
	}

	public void setEntFk(Long entFk) {
		this.entFk = entFk;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DestinosId))
			return false;
		DestinosId castOther = (DestinosId) other;

		return (this.getEntFk() == castOther.getEntFk())
				&& (this.getUsuFk() == castOther.getUsuFk());
	}

	public int hashCode() {
		int result = 17;

		result = (int) (37 * result + (Long) this.getEntFk());
		result = (int) (37 * result + this.getUsuFk());
		return result;
	}

}
