package business.beans;

// Generated 14-may-2009 22:46:18 by Hibernate Tools 3.2.4.GA

/**
 * Destinos generated by hbm2java
 */
public class Destinos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6640107723083474751L;
	private DestinosId id;
	private Entradas entradas;

	public Destinos() {
	}

	public Destinos(DestinosId id, Entradas entradas) {
		this.id = id;
		this.entradas = entradas;
	}

	public DestinosId getId() {
		return this.id;
	}

	public void setId(DestinosId id) {
		this.id = id;
	}

	public Entradas getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Entradas entradas) {
		this.entradas = entradas;
	}

}
