package business.beans;

// Generated 14-may-2009 22:46:18 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Entradas generated by hbm2java
 */
public class Entradas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3042780878410747457L;
	private Long entPk;
	private Long entFechaAlta;
	private String entSubject;
	private Long usuFk;
	private Boolean entRestringida;
	private Set<Destinos> destinoses = new HashSet<Destinos>(0);

	public Entradas() {
	}

	public Entradas(long entFechaAlta, String entSubject, Long usuFk) {
		this.entFechaAlta = entFechaAlta;
		this.entSubject = entSubject;
		this.usuFk = usuFk;
	}

	public Entradas(long entFechaAlta, String entSubject, String entCuerpo,
			Long usuFk, Set<Destinos> destinoses) {
		this.entFechaAlta = entFechaAlta;
		this.entSubject = entSubject;
		this.usuFk = usuFk;
		this.destinoses = destinoses;
	}

	public Long getEntPk() {
		return this.entPk;
	}

	public void setEntPk(Long entPk) {
		this.entPk = entPk;
	}

	public long getEntFechaAlta() {
		return this.entFechaAlta;
	}

	public void setEntFechaAlta(long entFechaAlta) {
		this.entFechaAlta = entFechaAlta;
	}

	public String getEntSubject() {
		return this.entSubject;
	}

	public void setEntSubject(String entSubject) {
		this.entSubject = entSubject;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public void setEntRestringida(Boolean entRestringida) {
		this.entRestringida = entRestringida;
	}

	public Boolean getEntRestringida() {
		return entRestringida;
	}

	public Set<Destinos> getDestinoses() {
		return this.destinoses;
	}

	public void setDestinoses(Set<Destinos> destinoses) {
		this.destinoses = destinoses;
	}

}
