package business.beans;

// Generated 01-may-2009 12:30:10 by Hibernate Tools 3.2.4.GA

/**
 * Parametros generated by hbm2java
 */
public class Parametros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1975387414592830776L;
	private String parPk;
	private String parValor;
	private String parDescripcion;

	public Parametros() {
	}

	public Parametros(String parPk, String parValor) {
		this.parPk = parPk;
		this.parValor = parValor;
	}

	public Parametros(String parPk, String parValor, String parDescripcion) {
		this.parPk = parPk;
		this.parValor = parValor;
		this.parDescripcion = parDescripcion;
	}

	public String getParPk() {
		return this.parPk;
	}

	public void setParPk(String parPk) {
		this.parPk = parPk;
	}

	public String getParValor() {
		return this.parValor;
	}

	public void setParValor(String parValor) {
		this.parValor = parValor;
	}

	public String getParDescripcion() {
		return this.parDescripcion;
	}

	public void setParDescripcion(String parDescripcion) {
		this.parDescripcion = parDescripcion;
	}

}
