package common.dto;

import common.presentation.beans.HtmlEvents;


// Generated 09-feb-2009 23:05:40 by Hibernate Tools 3.2.4.CR1

/**
 * Bugs generated by hbm2java
 */
public class BugsDTO extends HtmlEvents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7126791316206222404L;
	private Long bugPk;
	private Long bugSite;
	private String bugMessage;
	private String bugDescripcion;
	private Long usuFk;
	private Long bugFechaReport;
	private Long bugEstFk;
	private Long bugPriFk;

	private String usuUkCodigo; 
	private String usuNombre; 
	private String usuApellido1;
	private String usuApellido2; 
	private String zonUkCodigo; 
	private String zonDescripcion; 
	private String bugEstUkCodigo; 
	private String bugPriUkCodigo;
	
	private String bugIcon;
	private String style;

	
	public Long getBugPk() {
		return this.bugPk;
	}

	public void setBugPk(Long bugPk) {
		this.bugPk = bugPk;
	}

	public Long getBugSite() {
		return this.bugSite;
	}

	public void setBugSite(Long bugSite) {
		this.bugSite = bugSite;
	}

	public String getBugMessage() {
		return this.bugMessage;
	}

	public void setBugMessage(String bugMessage) {
		this.bugMessage = bugMessage;
	}

	public String getBugDescripcion() {
		return this.bugDescripcion;
	}

	public void setBugDescripcion(String bugDescripcion) {
		this.bugDescripcion = bugDescripcion;
	}

	public Long getUsuFk() {
		return this.usuFk;
	}

	public void setUsuFk(Long usuFk) {
		this.usuFk = usuFk;
	}

	public Long getBugFechaReport() {
		return this.bugFechaReport;
	}

	public void setBugFechaReport(Long bugFechaReport) {
		this.bugFechaReport = bugFechaReport;
	}

	public void setBugEstFk(Long bugEstFk) {
		this.bugEstFk = bugEstFk;
	}

	public Long getBugEstFk() {
		return bugEstFk;
	}

	public void setBugPriFk(Long bugPriFk) {
		this.bugPriFk = bugPriFk;
	}

	public Long getBugPriFk() {
		return bugPriFk;
	}

	public void setUsuUkCodigo(String usuUkCodigo) {
		this.usuUkCodigo = usuUkCodigo;
	}

	public String getUsuUkCodigo() {
		return usuUkCodigo;
	}

	public void setUsuNombre(String usuNombre) {
		this.usuNombre = usuNombre;
	}

	public String getUsuNombre() {
		return usuNombre;
	}

	public void setUsuApellido1(String usuApellido1) {
		this.usuApellido1 = usuApellido1;
	}

	public String getUsuApellido1() {
		return usuApellido1;
	}

	public void setUsuApellido2(String usuApellido2) {
		this.usuApellido2 = usuApellido2;
	}

	public String getUsuApellido2() {
		return usuApellido2;
	}

	public void setZonUkCodigo(String zonUkCodigo) {
		this.zonUkCodigo = zonUkCodigo;
	}

	public String getZonUkCodigo() {
		return zonUkCodigo;
	}

	public void setZonDescripcion(String zonDescripcion) {
		this.zonDescripcion = zonDescripcion;
	}

	public String getZonDescripcion() {
		return zonDescripcion;
	}

	public void setBugEstUkCodigo(String bugEstUkCodigo) {
		this.bugEstUkCodigo = bugEstUkCodigo;
	}

	public String getBugEstUkCodigo() {
		return bugEstUkCodigo;
	}

	public void setBugPriUkCodigo(String bugPriUkCodigo) {
		this.bugPriUkCodigo = bugPriUkCodigo;
	}

	public String getBugPriUkCodigo() {
		return bugPriUkCodigo;
	}

	public void setBugIcon(String bugIcon) {
		this.bugIcon = bugIcon;
	}

	public String getBugIcon() {
		return bugIcon;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getStyle() {
		return style;
	}
}
