package common.dto;

import java.util.Date;

// Generated 14-ene-2009 19:22:13 by Hibernate Tools 3.2.4.CR1

/**
 * Sessions generated by hbm2java
 */
public class SessionsDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8654205789536089724L;
	private Long sessionPk;
	private String sessionId;
	private String shareSessionId;
	private String address;
	private char validSession;
	private int maxInactive;
	private Date creationTime;
	private Date lastAccessedTime;
	private String appName;
	private byte[] sessionData;
	private Long userId;
	private Date closedTime;

	public Long getSessionPk() {
		return this.sessionPk;
	}

	public void setSessionPk(Long sessionPk) {
		this.sessionPk = sessionPk;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getShareSessionId() {
		return this.shareSessionId;
	}

	public void setShareSessionId(String shareSessionId) {
		this.shareSessionId = shareSessionId;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

	public char getValidSession() {
		return this.validSession;
	}

	public void setValidSession(char validSession) {
		this.validSession = validSession;
	}

	public int getMaxInactive() {
		return this.maxInactive;
	}

	public void setMaxInactive(int maxInactive) {
		this.maxInactive = maxInactive;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	public Date getLastAccessedTime() {
		return this.lastAccessedTime;
	}

	public void setLastAccessedTime(Date lastAccessedTime) {
		this.lastAccessedTime = lastAccessedTime;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public byte[] getSessionData() {
		return this.sessionData;
	}

	public void setSessionData(byte[] sessionData) {
		this.sessionData = sessionData;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public void setClosedTime(Date closedTime) {
		this.closedTime = closedTime;
	}

	public Date getClosedTime() {
		return closedTime;
	}

}
